// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zkiiqxoclpexgndtkbyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpraWlxeG9jbHBleGduZHRrYnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNTk1MTYsImV4cCI6MjA4MjkzNTUxNn0.tOIFYuJ8fK1VfgOLS4vSI_mok8oHBiMnRk_MTVmH3p4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);